#!/bin/sh

# restore wallpaper
#HOME/.config/bspwm/.fehbg
nitrogen --restore &

# wallpaper slide show
#$HOME/.config/bspwm/nitrogen-wallpaper-slide.sh

#LAUNCHERS
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/scripts/launch-polybar.sh

#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          35
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM COLORING
bspc config border_width         2
bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#282e3a"

nohup $HOME/.config/bspwm/bspborders &

#### MONITORS ####

# triple monitors
bspc query -M --names

###This creates and names desktops for multiple monitors.
workspaces_multimonitor &

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor DP-0   -d I II III IV V VI VII VIII
bspc monitor HDMI-0 -d I II III IV V VI VII VIII
#bspc monitor DVI-D-0 -d I II III IV V VI VII VIII IX

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#Open applications on specific workspaces
#Workspaces desktop DP-0
bspc rule -a konsole:konsole desktop='^1'  follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a dolphin:dolphin desktop='^3' follow=on
bspc rule -a Geany desktop='^4' follow=on
bspc rule -a Vivaldi-snapshot desktop='^5' follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Pamac-manager state=tile desktop='^8' follow=on
#Workspaces desktop HDMI-0
bspc rule -a kitty:kitty desktop='^9'  follow=on
bspc rule -a Brave-browser desktop='^10' follow=on
bspc rule -a Whatsapp-for-linux desktop='^11' follow=on
bspc rule -a discord desktop='^12' follow=on
bspc rule -a Variety:Variety state=tiled desktop='^13' follow=on
bspc rule -a Nitrogen state=tiled desktop='^14' follow=on
bspc rule -a VirtualBox state=fullscreen desktop='^15' follow=on
bspc rule -a Xfce4-settings-manager state=tiled desktop='^16' follow=on

#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

polybar hidden when fullscreen for vlc, youtube,arcolinux-logout mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-left_DP-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-middle_HDMI-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-right_DVI-D-0)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

#do
    #bsp-layout set tall $i -- --master-size 0.65 &
    #done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww caffeine firewall-applet

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# fix pointer
xsetroot -cursor_name left_ptr


# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


numlockx on &

# Launch keybindings daemon
sxhkd &

# start lxsession
lxsession &

# start tray icon plasma
pamac-tray &

# start caffeine-ng
#caffeine &

# start variety
#variety &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"norchad\",/g" $HOME/.config/nvim/lua/custom/norchad.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/nord "$XFCE_TERM_PATH"/terminalrc

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &


datetime(){
    datetime=`date +\ %A\ %B\ %Y\ \|\ \\ %H\:%M`
    echo "$datetime"
}

