#!/bin/sh

# restore wallpaper
#HOME/.config/bspwm/.fehbg

# wallpaper slide show
#$HOME/.config/bspwm/nitrogen-wallpaper-slide.sh

#LAUNCHERS
$HOME/.config/polybar/launch.sh
# Reloads polybar instance on start for the volume module
~/.config/polybar/scripts/polybar-reload.sh

# sets the layout of each desktop
~/.config/bspwm/scripts/desktop-layout.sh


#### MONITORS ####

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

#  monitors names query
bspc query -M --names

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc monitor eDP -d I II III IV V VI VII VIII 
bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII 

#bspc monitor eDP -d '' '' '' '' '' '' '' ''
#bspc monitor HDMI-A-0 -d '' '' '' '' '' '' '' ''

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          35
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM COLORING
bspc config focused_border_color "#FD807E"
bspc config normal_border_color "#282e3a"

#Fullscreen applications
#bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
bspc rule -a popup-calendar state=floating
#bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating
bspc rule -a konsole state=tiled

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#Open applications on specific workspaces
#Workspaces desktop eDP
bspc rule -a konsole:konsole desktop='^9'  follow=on
bspc rule -a vlc desktop='^7' follow=on
bspc rule -a Transmission-gtk desktop='^7' follow=on

#Workspaces desktop HDMI-A-0
bspc rule -a kitty:kitty desktop='^9'  follow=on
bspc rule -a Xfce4-terminal desktop='^9'  follow=on
bspc rule -a Brave-browser desktop='^10' follow=on
bspc rule -a Firefox desktop='^10' follow=on
bspc rule -a Chromium desktop='^10' follow=on
bspc rule -a dolphin:dolphin desktop='^11' follow=on
bspc rule -a Thunar desktop='^10' follow=on
bspc rule -a Geany desktop='^12' follow=on
bspc rule -a Vivaldi-snapshot desktop='^13' follow=on
bspc rule -a VirtualBox state=fullscreen desktop='^14' follow=on
bspc rule -a Nitrogen state=tiled desktop='^15' follow=on
bspc rule -a Variety:Variety state=tiled desktop='^15' follow=on
#bspc rule -a discord desktop='^14' follow=on
#bspc rule -a Whatsapp-for-linux desktop='^14' follow=on
bspc rule -a guvcview desktop='^15' follow=on
bspc rule -a Pamac-manager state=tile desktop='^16' follow=on
bspc rule -a Xfce4-settings-manager state=tiled desktop='^16' follow=on


#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on


polybar hidden when fullscreen for vlc, youtube,arcolinux-logout mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-smallscreen_eDP)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-bigscreen HDMI-A-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-right_DVI-D-0)

## Autostart -------------------------------------------------#

# Set display from arandr saved script
sh ~/.screenlayout/.screenlayout.sh &

# Kill if already running
killall -9 picom sxhkd dunst polkit-gnome-authentication-agent-1 

# Launch notification daemon
/usr/bin/dunst &


# fix pointer
xsetroot -Breeze_Snow left_ptr

# polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Set number lock on #### Set number lock on ##
numlockx on &

# Launch keybindings daemon
# Make sure sxhkd is always running
sxhkd &


# start LXAppearance
#lxappearance &

# start lxsession
#lxsession &

#rule to show plank above windows
#bspc rule -a Plank layer=above manage=on border=off

# plank
#XDG_SESSION_TYPE=X11
#plank &


# start tray icon plasma
#pamac-tray &

# start caffeine-ng
#caffeine &

##Wallpaper. Nitrogen just draws wallpaper
sleep 2 && nitrogen --restore &

# start variety
#variety &

# Enable power management
#xfce4-power-manager &

##powersaving options
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &
xbacklight -set 100 &

# replace neovim colorscheme
#sed -i "s/theme =.*$/theme = \"norchad\",/g" $HOME/.config/nvim/lua/custom/norchad.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/nord "$XFCE_TERM_PATH"/terminalrc

##compositing. Required for shadows, transparency and stuff. 
##Reduces flicker. Disabling saves resources.
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &


datetime(){
    datetime=`date +\ %A\ %B\ %Y\ \|\ \\ %H\:%M`
    echo "$datetime"
}

