#!/usr/bin/env bash

maxvol=200

vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

if [ $vol -lt $maxvol ]
then
    pactl set-sink-volume @DEFAULT_SINK@ +5%
fi
